//! Direct Kusto streaming ingestion.
//!
//! The REST protocol accepts a raw request body (or a JSON `{sourceUri: ...}`
//! body for an existing URI).  It intentionally does not accept queued
//! ingestion properties such as extent tags or inline mappings.
const std = @import("std");
const serde = @import("serde");
const core = @import("azure_core");
const kusto_common = @import("azure_kusto_common");

pub const DataFormat = kusto_common.DataFormat;
pub const ConnectionProperties = kusto_common.ConnectionProperties;
pub const KustoConnection = kusto_common.KustoConnection;
pub const KustoError = kusto_common.KustoError;
pub const KustoOperationOutcome = kusto_common.KustoOperationOutcome;
pub const KustoResult = kusto_common.KustoResult;

/// Maximum uncompressed source size accepted by Kusto streaming ingestion.
/// The service's 4 MB limit also includes data generated by update policies.
pub const max_streaming_payload_bytes: u64 = 4 * 1024 * 1024;

/// The target of one direct streaming ingestion operation.
pub const StreamingIngestTarget = struct {
    database: []const u8,
    table: []const u8,
};

/// How request bytes are encoded on the wire.
pub const RequestCompression = enum {
    none,
    gzip,
};

/// Describes a reader opened by a replay factory.
///
/// `deinitFn`, when supplied, is called exactly once after `HttpPipeline.open`
/// returns, including when opening or uploading fails. It should release any
/// factory-owned resource associated with this reader.
pub const ReplayReader = struct {
    reader: *std.Io.Reader,
    context: ?*anyopaque = null,
    deinitFn: ?*const fn (context: ?*anyopaque) void = null,

    pub fn deinit(self: *ReplayReader) void {
        if (self.deinitFn) |deinit_fn| deinit_fn(self.context);
        self.* = undefined;
    }
};

/// Opens a fresh reader for each attempt. The factory and every reader it
/// returns are borrowed by the ingestion call.
pub const ReplayReaderFactory = struct {
    context: *anyopaque,
    openFn: *const fn (context: *anyopaque) anyerror!ReplayReader,
    /// Exact uncompressed byte length, required so the client can enforce the
    /// streaming limit before transport entry.
    raw_size: u64,

    pub fn open(self: ReplayReaderFactory) !ReplayReader {
        return self.openFn(self.context);
    }
};

/// A borrowed, one-shot source. It is consumed only by the first transport
/// attempt and never retried automatically.
pub const BorrowedReaderSource = struct {
    reader: *std.Io.Reader,
    /// Exact uncompressed byte length, required for direct streaming.
    raw_size: ?u64 = null,
};

/// A reference to existing storage. The direct streaming endpoint supports
/// this only through `sourceKind=uri` and a JSON `{ "sourceUri": ... }` body.
pub const BlobUriSource = struct {
    uri: []const u8,
    /// Exact uncompressed blob size, used for local limit enforcement.
    raw_size: ?u64 = null,
};

pub const SourceKind = enum {
    bytes,
    file,
    reader,
    replay_reader,
    blob_uri,
};

/// Runtime source for direct streaming ingestion.
///
/// Byte slices and paths are borrowed for the duration of the call. Local
/// files are reopened for every retry. A `reader` is never retried; use
/// `replay_reader` only when the supplied factory can safely produce an
/// independent reader for every retry.
pub const StreamingIngestSource = union(enum) {
    bytes: []const u8,
    file: []const u8,
    reader: BorrowedReaderSource,
    replay_reader: ReplayReaderFactory,
    blob_uri: BlobUriSource,

    pub fn kind(self: StreamingIngestSource) SourceKind {
        return switch (self) {
            .bytes => .bytes,
            .file => .file,
            .reader => .reader,
            .replay_reader => .replay_reader,
            .blob_uri => .blob_uri,
        };
    }

    pub fn isReplayable(self: StreamingIngestSource) bool {
        return switch (self) {
            .reader => false,
            .bytes, .file, .replay_reader, .blob_uri => true,
        };
    }
};

/// Typed validation-policy shape used by queued ingestion protocols. Direct
/// streaming does not support it, so a non-null value is rejected locally.
pub const ValidationPolicy = struct {
    validation_options: ?u32 = null,
    validation_implications: ?u32 = null,
};

/// Bounded Kusto-layer retry options. Generic pipeline retries remain disabled
/// for every streaming request because an upload body is consumed by `open`.
pub const StreamingRetryOptions = struct {
    /// Retries after a received retryable non-2xx response. A retry is made
    /// only when `source` is explicitly replayable.
    max_retries: u32 = 1,
    initial_delay_ms: u64 = 200,
    max_delay_ms: u64 = 10_000,
};

/// Options supported by direct streaming ingestion.
///
/// Named mappings are supported by the REST endpoint. Extent tags, creation
/// times, validation policies, inline mappings, and first-record skipping are
/// queued-ingestion properties; direct streaming rejects them before opening a
/// transport operation rather than silently dropping them.
pub const IngestOptions = struct {
    format: DataFormat = .csv,
    /// Existing public spelling retained for source compatibility.
    mapping_name: ?[]const u8 = null,
    /// Logical source identifier. It remains unchanged on every replay and is
    /// sent as `x-ms-client-request-id`. An ID is generated if absent.
    source_id: ?[]const u8 = null,
    /// If supplied, must match the exact raw source length.
    raw_size: ?u64 = null,
    compression: RequestCompression = .gzip,
    retry: StreamingRetryOptions = .{},
    cancellation: ?*const core.http.CancellationToken = null,

    /// Kept for source compatibility. Direct writes are already immediate.
    flush_immediately: bool = false,

    /// Unsupported by direct streaming and validated before transmission.
    creation_time_unix_ms: ?i64 = null,
    validation_policy: ?ValidationPolicy = null,
    tags: []const []const u8 = &.{},
    ingest_if_not_exists: []const []const u8 = &.{},
    ignore_first_record: bool = false,
};

pub const IngestionStatus = enum {
    success,
    queued,
    failed,

    pub fn toString(self: IngestionStatus) []const u8 {
        return switch (self) {
            .success => "Success",
            .queued => "Queued",
            .failed => "Failed",
        };
    }
};

pub const IngestionResult = struct {
    status: IngestionStatus,
    outcome: KustoOperationOutcome = .accepted,
    /// Allocator-owned logical source ID; call `deinit` when finished.
    ingestion_id: ?[]const u8 = null,
    source_kind: ?SourceKind = null,

    pub fn deinit(self: *IngestionResult, allocator: std.mem.Allocator) void {
        if (self.ingestion_id) |id| allocator.free(id);
        self.* = .{ .status = self.status, .outcome = self.outcome };
    }
};

/// Direct streaming ingestion via the Kusto engine endpoint.
pub const StreamingIngestClient = struct {
    runtime: Runtime,

    const Runtime = union(enum) {
        legacy: struct {
            connection: ConnectionProperties,
            pipeline: core.pipeline.HttpPipeline,
        },
        shared: *KustoConnection,
    };

    pub fn init(
        connection: ConnectionProperties,
        transport: *core.http.HttpTransport,
    ) StreamingIngestClient {
        return .{
            .runtime = .{ .legacy = .{
                .connection = connection,
                .pipeline = .{ .policies = &.{}, .transport_impl = transport },
            } },
        };
    }

    /// Creates a client borrowing an authenticated shared Kusto connection.
    pub fn initWithConnection(connection: *KustoConnection) StreamingIngestClient {
        return .{ .runtime = .{ .shared = connection } };
    }

    /// Ingests a runtime source. Service failures are logged and returned as a
    /// failed result; use `ingestResult` to inspect the structured outcome.
    pub fn ingest(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        source: StreamingIngestSource,
        options: IngestOptions,
    ) !IngestionResult {
        var result = try self.ingestResult(allocator, target, source, options);
        return switch (result) {
            .ok => |value| value,
            .partial => unreachable,
            .err => |*failure| blk: {
                const outcome = failure.outcome;
                std.log.warn("{f}", .{failure.*});
                failure.deinit();
                break :blk .{
                    .status = .failed,
                    .outcome = outcome,
                    .source_kind = source.kind(),
                };
            },
        };
    }

    /// Ingests a runtime source and exposes received Kusto failures as `.err`.
    ///
    /// A non-2xx response is known not accepted and may be retried only after
    /// reopening an explicit replayable source. Any failure while opening or
    /// uploading after transport entry has an unknown outcome and is never
    /// replayed.
    pub fn ingestResult(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        source: StreamingIngestSource,
        options: IngestOptions,
    ) !KustoResult(IngestionResult) {
        const prepared = try prepareSource(source, options);
        try validateOptions(target, source.kind(), options, prepared.raw_size);

        const logical_source_id = try makeLogicalSourceId(allocator, options.source_id);
        var source_id_owned = true;
        defer if (source_id_owned) allocator.free(logical_source_id);

        const url = try self.buildIngestUrl(allocator, target, options, source.kind());
        defer allocator.free(url);

        var retries: u32 = 0;
        while (true) {
            var attempt = try self.ingestAttempt(
                allocator,
                url,
                source,
                prepared.raw_size,
                logical_source_id,
                options,
            );
            switch (attempt) {
                .err => |*failure| {
                    if (!source.isReplayable() or
                        !failure.retryable or
                        failure.outcome != .known_not_accepted or
                        retries >= options.retry.max_retries)
                    {
                        return attempt;
                    }
                    const delay_ms = retryDelayMs(options.retry, retries, failure.retry_after_ms);
                    failure.deinit();
                    retries += 1;
                    try sleepForRetry(delay_ms, options.cancellation);
                },
                .ok => |*ingestion| {
                    ingestion.ingestion_id = logical_source_id;
                    source_id_owned = false;
                    return attempt;
                },
                .partial => unreachable,
            }
        }
    }

    /// Existing slice wrapper retained for source compatibility.
    pub fn ingestFromSlice(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        database: []const u8,
        table: []const u8,
        data: []const u8,
        options: IngestOptions,
    ) !IngestionResult {
        return self.ingest(allocator, .{ .database = database, .table = table }, .{ .bytes = data }, options);
    }

    /// Existing slice wrapper retained for source compatibility.
    pub fn ingestFromSliceResult(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        database: []const u8,
        table: []const u8,
        data: []const u8,
        options: IngestOptions,
    ) !KustoResult(IngestionResult) {
        return self.ingestResult(
            allocator,
            .{ .database = database, .table = table },
            .{ .bytes = data },
            options,
        );
    }

    /// Convenience wrapper for a borrowed one-shot reader.
    pub fn ingestFromReaderResult(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        reader: *std.Io.Reader,
        raw_size: u64,
        options: IngestOptions,
    ) !KustoResult(IngestionResult) {
        return self.ingestResult(
            allocator,
            target,
            .{ .reader = .{ .reader = reader, .raw_size = raw_size } },
            options,
        );
    }

    /// Convenience wrapper for a borrowed one-shot reader.
    pub fn ingestFromReader(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        reader: *std.Io.Reader,
        raw_size: u64,
        options: IngestOptions,
    ) !IngestionResult {
        return self.ingest(
            allocator,
            target,
            .{ .reader = .{ .reader = reader, .raw_size = raw_size } },
            options,
        );
    }

    /// Convenience wrapper for a local path. The file is reopened for a
    /// retry, never loaded wholly into memory.
    pub fn ingestFromFileResult(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        path: []const u8,
        options: IngestOptions,
    ) !KustoResult(IngestionResult) {
        return self.ingestResult(allocator, target, .{ .file = path }, options);
    }

    /// Convenience wrapper for a local path. The file is streamed from disk
    /// and is never loaded wholly into memory.
    pub fn ingestFromFile(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        path: []const u8,
        options: IngestOptions,
    ) !IngestionResult {
        return self.ingest(allocator, target, .{ .file = path }, options);
    }

    fn ingestAttempt(
        self: *StreamingIngestClient,
        allocator: std.mem.Allocator,
        url: []const u8,
        source: StreamingIngestSource,
        raw_size: u64,
        source_id: []const u8,
        options: IngestOptions,
    ) !KustoResult(IngestionResult) {
        var opened = try OpenedSource.init(allocator, source, raw_size);
        defer opened.deinit();

        var request = core.http.Request.init(allocator, .POST, url);
        defer request.deinit();
        try request.setHeader("Accept", "application/json");
        try request.setHeader("Accept-Encoding", "gzip, deflate");
        try request.setHeader("x-ms-app", "azure-sdk-zig");
        try request.setHeader("x-ms-client-request-id", source_id);
        request.retryable = false;

        var body: core.http.StreamingRequestBody = undefined;
        var gzip_reader: ?*GzipReader = null;
        defer if (gzip_reader) |reader| allocator.destroy(reader);

        if (source.kind() == .blob_uri) {
            try request.setHeader("Content-Type", "application/json; charset=utf-8");
            body = .{ .reader = opened.reader(), .content_length = opened.contentLength() };
        } else {
            try request.setHeader("Content-Type", "application/octet-stream");
            switch (options.compression) {
                .none => body = .{ .reader = opened.reader(), .content_length = raw_size },
                .gzip => {
                    try request.setHeader("Content-Encoding", "gzip");
                    const reader = try allocator.create(GzipReader);
                    errdefer allocator.destroy(reader);
                    try reader.init(opened.reader(), raw_size);
                    gzip_reader = reader;
                    body = .{ .reader = &reader.interface, .content_length = null };
                },
            }
        }

        const operation = self.open(&request, .{
            .body = body,
            .cancellation = options.cancellation,
        }) catch |err| {
            if (request.transport_started) {
                return .{ .err = try kusto_common.errors.transportUnknown(
                    allocator,
                    err,
                    source_id,
                ) };
            }
            return err;
        };
        defer operation.deinit();

        if (!operation.isSuccess()) {
            var response = try responseFromOperation(allocator, operation);
            defer response.deinit();
            var failure = try kusto_common.errors.fromHttpResponse(
                allocator,
                .streaming_ingest,
                &response,
                .known_not_accepted,
            );
            errdefer failure.deinit();
            try kusto_common.errors.applyResponseCorrelation(&failure, &response, source_id);
            return .{ .err = failure };
        }

        operation.finish() catch |err| {
            return .{ .err = try kusto_common.errors.transportUnknown(allocator, err, source_id) };
        };
        return .{ .ok = .{
            .status = .success,
            .source_kind = source.kind(),
        } };
    }

    fn buildIngestUrl(
        self: *const StreamingIngestClient,
        allocator: std.mem.Allocator,
        target: StreamingIngestTarget,
        options: IngestOptions,
        source_kind: SourceKind,
    ) ![]u8 {
        const encoded_database = try core.url.percentEncode(allocator, target.database);
        defer allocator.free(encoded_database);
        const encoded_table = try core.url.percentEncode(allocator, target.table);
        defer allocator.free(encoded_table);

        const endpoint = switch (self.runtime) {
            .legacy => |legacy| legacy.connection.cluster_url,
            .shared => |connection| connection.engineUrl(),
        };

        var query = std.ArrayList(u8).empty;
        defer query.deinit(allocator);
        try query.appendSlice(allocator, "streamFormat=");
        try query.appendSlice(allocator, options.format.toString());
        if (options.mapping_name) |mapping_name| {
            const mapping = try core.url.percentEncode(allocator, mapping_name);
            defer allocator.free(mapping);
            try query.appendSlice(allocator, "&mappingName=");
            try query.appendSlice(allocator, mapping);
        }
        if (source_kind == .blob_uri) try query.appendSlice(allocator, "&sourceKind=uri");

        return std.fmt.allocPrint(
            allocator,
            "{s}/v1/rest/ingest/{s}/{s}?{s}",
            .{ endpoint, encoded_database, encoded_table, query.items },
        );
    }

    fn open(
        self: *StreamingIngestClient,
        request: *core.http.Request,
        options: core.http.OpenOptions,
    ) !*core.http.HttpOperation {
        return switch (self.runtime) {
            .shared => |connection| connection.open(request, options),
            .legacy => |*legacy| {
                if (connectionHasAuthentication(legacy.connection))
                    return error.AuthenticatedConnectionRequired;
                return legacy.pipeline.open(request, options);
            },
        };
    }
};

fn connectionHasAuthentication(connection: ConnectionProperties) bool {
    return connection.credential != null or
        connection.application_client_id != null or
        connection.application_key != null or
        connection.authority_id != null;
}

const PreparedSource = struct {
    raw_size: u64,
};

fn prepareSource(source: StreamingIngestSource, options: IngestOptions) !PreparedSource {
    const raw_size = switch (source) {
        .bytes => |bytes| @as(u64, @intCast(bytes.len)),
        .reader => |reader| reader.raw_size orelse return error.StreamingRawSizeRequired,
        .replay_reader => |factory| factory.raw_size,
        .blob_uri => |blob| blob.raw_size orelse return error.StreamingRawSizeRequired,
        .file => |path| try fileSize(path),
    };
    if (raw_size > max_streaming_payload_bytes) return error.StreamingPayloadTooLarge;
    if (options.raw_size) |expected| {
        if (expected != raw_size) return error.StreamingRawSizeMismatch;
    }
    return .{ .raw_size = raw_size };
}

fn validateOptions(
    target: StreamingIngestTarget,
    source_kind: SourceKind,
    options: IngestOptions,
    raw_size: u64,
) !void {
    if (target.database.len == 0 or !std.unicode.utf8ValidateSlice(target.database))
        return error.InvalidStreamingDatabase;
    if (target.table.len == 0 or !std.unicode.utf8ValidateSlice(target.table))
        return error.InvalidStreamingTable;
    if (options.mapping_name) |mapping_name| {
        if (mapping_name.len == 0 or !std.unicode.utf8ValidateSlice(mapping_name))
            return error.InvalidStreamingMappingName;
    }
    switch (options.format) {
        .csv, .tsv, .scsv, .sohsv, .psv, .json, .multi_json, .avro => {},
        else => return error.StreamingFormatUnsupported,
    }
    switch (options.format) {
        .json, .multi_json, .avro => {
            if (options.mapping_name == null)
                return error.StreamingMappingRequired;
        },
        else => {},
    }
    if (options.source_id) |source_id| try validateSourceId(source_id);
    if (raw_size > max_streaming_payload_bytes) return error.StreamingPayloadTooLarge;
    if (options.creation_time_unix_ms != null)
        return error.StreamingCreationTimeUnsupported;
    if (options.validation_policy != null)
        return error.StreamingValidationPolicyUnsupported;
    if (options.tags.len != 0 or options.ingest_if_not_exists.len != 0)
        return error.StreamingExtentTagsUnsupported;
    if (options.ignore_first_record)
        return error.StreamingIgnoreFirstRecordUnsupported;
    if (source_kind == .blob_uri and options.compression != .none)
        return error.StreamingUriCompressionUnsupported;
}

fn validateSourceId(source_id: []const u8) !void {
    if (source_id.len == 0 or !std.unicode.utf8ValidateSlice(source_id))
        return error.InvalidStreamingSourceId;
    for (source_id) |byte| {
        if (byte < 0x20 or byte == 0x7f) return error.InvalidStreamingSourceId;
    }
}

fn makeLogicalSourceId(allocator: std.mem.Allocator, provided: ?[]const u8) ![]u8 {
    if (provided) |source_id| {
        try validateSourceId(source_id);
        return allocator.dupe(u8, source_id);
    }
    var threaded: std.Io.Threaded = .init_single_threaded;
    const timestamp = std.Io.Timestamp.now(threaded.io(), .real).toNanoseconds();
    var prng = std.Random.DefaultPrng.init(@truncate(@as(u96, @bitCast(timestamp))));
    const uuid = core.uuid.Uuid.init(prng.random()).toString();
    return allocator.dupe(u8, &uuid);
}

fn retryDelayMs(
    options: StreamingRetryOptions,
    attempt: u32,
    server_delay_ms: ?u64,
) u64 {
    if (server_delay_ms) |delay|
        return @min(delay, options.max_delay_ms);
    if (options.initial_delay_ms == 0 or options.max_delay_ms == 0)
        return 0;
    if (attempt >= 63) return options.max_delay_ms;
    const multiplier = @as(u64, 1) << @intCast(attempt);
    const scaled = std.math.mul(u64, options.initial_delay_ms, multiplier) catch
        std.math.maxInt(u64);
    return @min(scaled, options.max_delay_ms);
}

fn sleepForRetry(
    delay_ms: u64,
    cancellation: ?*const core.http.CancellationToken,
) !void {
    var remaining = delay_ms;
    var threaded: std.Io.Threaded = .init_single_threaded;
    while (remaining != 0) {
        if (cancellation) |token| {
            if (token.isCancelled()) return error.OperationCancelled;
        }
        const chunk = @min(remaining, 100);
        threaded.io().sleep(.fromMilliseconds(@intCast(chunk)), .awake) catch {};
        remaining -= chunk;
    }
    if (cancellation) |token| {
        if (token.isCancelled()) return error.OperationCancelled;
    }
}

fn fileSize(path: []const u8) !u64 {
    var threaded: std.Io.Threaded = .init_single_threaded;
    const io = threaded.io();
    var file = try std.Io.Dir.cwd().openFile(io, path, .{});
    defer file.close(io);
    const stat = try file.stat(io);
    if (stat.kind != .file) return error.StreamingSourceNotFile;
    return stat.size;
}

const SourceUriWire = struct {
    sourceUri: []const u8,
};

const FileSourceHandle = struct {
    allocator: std.mem.Allocator,
    threaded: std.Io.Threaded,
    handle: std.Io.File,
    reader_impl: std.Io.File.Reader,
    buffer: [16 * 1024]u8 = undefined,

    fn deinit(self: *FileSourceHandle) void {
        self.handle.close(self.threaded.io());
        self.allocator.destroy(self);
    }
};

const OpenedSource = union(enum) {
    bytes: struct {
        reader_impl: std.Io.Reader,
    },
    file: *FileSourceHandle,
    borrowed: *std.Io.Reader,
    replay: ReplayReader,
    blob_uri: struct {
        allocator: std.mem.Allocator,
        body: []u8,
        reader_impl: std.Io.Reader,
    },

    fn init(
        allocator: std.mem.Allocator,
        source: StreamingIngestSource,
        expected_raw_size: u64,
    ) !OpenedSource {
        return switch (source) {
            .bytes => |bytes| .{ .bytes = .{ .reader_impl = std.Io.Reader.fixed(bytes) } },
            .reader => |source_reader| .{ .borrowed = source_reader.reader },
            .replay_reader => |factory| .{ .replay = try factory.open() },
            .blob_uri => |blob| blk: {
                if (blob.uri.len == 0 or !std.unicode.utf8ValidateSlice(blob.uri))
                    return error.InvalidStreamingSourceUri;
                const body = try serde.json.toSlice(allocator, SourceUriWire{ .sourceUri = blob.uri });
                errdefer allocator.free(body);
                break :blk .{ .blob_uri = .{
                    .allocator = allocator,
                    .body = body,
                    .reader_impl = std.Io.Reader.fixed(body),
                } };
            },
            .file => |path| blk: {
                const handle = try allocator.create(FileSourceHandle);
                errdefer allocator.destroy(handle);
                handle.* = .{
                    .allocator = allocator,
                    .threaded = .init_single_threaded,
                    .handle = undefined,
                    .reader_impl = undefined,
                };
                const io = handle.threaded.io();
                handle.handle = try std.Io.Dir.cwd().openFile(io, path, .{});
                errdefer handle.handle.close(io);
                const stat = try handle.handle.stat(io);
                if (stat.kind != .file) return error.StreamingSourceNotFile;
                if (stat.size != expected_raw_size) return error.StreamingSourceChanged;
                handle.reader_impl = handle.handle.readerStreaming(io, &handle.buffer);
                break :blk .{ .file = handle };
            },
        };
    }

    fn reader(self: *OpenedSource) *std.Io.Reader {
        return switch (self.*) {
            .bytes => |*bytes| &bytes.reader_impl,
            .file => |file| &file.reader_impl.interface,
            .borrowed => |borrowed_reader| borrowed_reader,
            .replay => |*replay| replay.reader,
            .blob_uri => |*blob_uri| &blob_uri.reader_impl,
        };
    }

    fn deinit(self: *OpenedSource) void {
        switch (self.*) {
            .file => |file| file.deinit(),
            .replay => |*replay| replay.deinit(),
            .blob_uri => |*blob_uri| blob_uri.allocator.free(blob_uri.body),
            .bytes, .borrowed => {},
        }
    }

    fn contentLength(self: *const OpenedSource) ?u64 {
        return switch (self.*) {
            .blob_uri => |blob_uri| @intCast(blob_uri.body.len),
            else => null,
        };
    }
};

/// Incrementally gzip-compresses a known-size source. It owns fixed-size
/// working storage only; source data is never accumulated.
const GzipReader = struct {
    interface: std.Io.Reader,
    source: *std.Io.Reader,
    raw_remaining: u64,
    source_checked: bool = false,
    finished: bool = false,
    source_buffer: [16 * 1024]u8 = undefined,
    output_buffer: [128 * 1024]u8 = undefined,
    output_writer: std.Io.Writer = undefined,
    output_pos: usize = 0,
    compressor_buffer: [std.compress.flate.max_window_len]u8 = undefined,
    compressor: std.compress.flate.Compress = undefined,

    fn init(self: *GzipReader, source: *std.Io.Reader, raw_size: u64) !void {
        self.* = .{
            .interface = .{
                .vtable = &.{ .stream = &stream },
                .buffer = &.{},
                .seek = 0,
                .end = 0,
            },
            .source = source,
            .raw_remaining = raw_size,
        };
        self.output_writer = .fixed(&self.output_buffer);
        self.compressor = try std.compress.flate.Compress.init(
            &self.output_writer,
            &self.compressor_buffer,
            .gzip,
            .fastest,
        );
    }

    fn stream(
        interface: *std.Io.Reader,
        writer: *std.Io.Writer,
        limit: std.Io.Limit,
    ) std.Io.Reader.StreamError!usize {
        const self: *GzipReader = @alignCast(@fieldParentPtr("interface", interface));
        while (true) {
            const pending = self.output_writer.buffer[self.output_pos..self.output_writer.end];
            if (pending.len != 0) {
                const count = writer.write(limit.slice(pending)) catch return error.WriteFailed;
                self.output_pos += count;
                if (self.output_pos == self.output_writer.end) {
                    self.output_pos = 0;
                    self.output_writer.end = 0;
                }
                return count;
            }
            if (self.finished) return error.EndOfStream;
            self.produce() catch return error.ReadFailed;
        }
    }

    fn produce(self: *GzipReader) !void {
        if (self.raw_remaining != 0) {
            const wanted: usize = @intCast(@min(self.raw_remaining, self.source_buffer.len));
            const count = try self.source.readSliceShort(self.source_buffer[0..wanted]);
            if (count == 0) return error.RequestBodyTooShort;
            self.raw_remaining -= count;
            try self.compressor.writer.writeAll(self.source_buffer[0..count]);
            return;
        }
        if (!self.source_checked) {
            var extra: [1]u8 = undefined;
            if (try self.source.readSliceShort(&extra) != 0) return error.RequestBodyTooLong;
            self.source_checked = true;
        }
        try self.compressor.finish();
        self.finished = true;
    }
};

/// Reads a received HTTP failure body with bounded allocation. A body read or
/// drain error cannot make a non-2xx response ambiguous, so it is ignored
/// after retaining the bytes already received.
fn responseFromOperation(
    allocator: std.mem.Allocator,
    operation: *core.http.HttpOperation,
) !core.http.Response {
    var output = std.ArrayList(u8).empty;
    errdefer output.deinit(allocator);
    const reader = try operation.reader();
    var buffer: [4 * 1024]u8 = undefined;
    while (output.items.len < 1024 * 1024) {
        const count = reader.readSliceShort(&buffer) catch break;
        if (count == 0) break;
        const remaining = 1024 * 1024 - output.items.len;
        try output.appendSlice(allocator, buffer[0..@min(remaining, count)]);
    }
    _ = operation.finish() catch {};

    var headers = std.StringHashMap([]const u8).init(allocator);
    errdefer deinitHeaders(allocator, &headers);
    var iterator = operation.headers.iterator();
    while (iterator.next()) |header| {
        const name = try allocator.dupe(u8, header.key_ptr.*);
        errdefer allocator.free(name);
        const value = try allocator.dupe(u8, header.value_ptr.*);
        errdefer allocator.free(value);
        const entry = try headers.getOrPut(name);
        if (entry.found_existing) {
            allocator.free(name);
            allocator.free(entry.value_ptr.*);
        } else {
            entry.key_ptr.* = name;
        }
        entry.value_ptr.* = value;
    }
    return .{
        .status_code = operation.status_code,
        .headers = headers,
        .body = try output.toOwnedSlice(allocator),
        .allocator = allocator,
    };
}

fn deinitHeaders(
    allocator: std.mem.Allocator,
    headers: *std.StringHashMap([]const u8),
) void {
    var iterator = headers.iterator();
    while (iterator.next()) |header| {
        allocator.free(header.key_ptr.*);
        allocator.free(header.value_ptr.*);
    }
    headers.deinit();
}

/// Typed JSON/NDJSON serialization helpers. They intentionally produce raw
/// source bytes; use `mapping` to create a named mapping separately because
/// inline mappings are not accepted by direct streaming.
pub fn JsonRows(comptime Row: type) type {
    return struct {
        pub const Serialized = struct {
            bytes: []u8,
            format: DataFormat,

            pub fn source(self: *const Serialized) StreamingIngestSource {
                return .{ .bytes = self.bytes };
            }

            pub fn deinit(self: *Serialized, allocator: std.mem.Allocator) void {
                allocator.free(self.bytes);
                self.* = undefined;
            }
        };

        const MappingProperties = struct {
            Path: []const u8,
        };
        const MappingEntry = struct {
            column: []const u8,
            Properties: MappingProperties,
        };

        pub fn json(allocator: std.mem.Allocator, rows: []const Row) !Serialized {
            return .{
                .bytes = try serde.json.toSlice(allocator, rows),
                .format = .multi_json,
            };
        }

        pub fn ndjson(allocator: std.mem.Allocator, rows: []const Row) !Serialized {
            var output = std.ArrayList(u8).empty;
            errdefer output.deinit(allocator);
            for (rows) |row| {
                const encoded = try serde.json.toSlice(allocator, row);
                output.appendSlice(allocator, encoded) catch |err| {
                    allocator.free(encoded);
                    return err;
                };
                output.append(allocator, '\n') catch |err| {
                    allocator.free(encoded);
                    return err;
                };
                allocator.free(encoded);
            }
            return .{
                .bytes = try output.toOwnedSlice(allocator),
                .format = .json,
            };
        }

        /// Returns a typed JSON mapping for a struct's field names. Create a
        /// named mapping with a management command, then use its name through
        /// `IngestOptions.mapping_name`.
        pub fn mapping(allocator: std.mem.Allocator) ![]u8 {
            const fields = std.meta.fields(Row);
            var entries: [fields.len]MappingEntry = undefined;
            var paths: [fields.len][]u8 = undefined;
            var path_count: usize = 0;
            defer for (paths[0..path_count]) |path| allocator.free(path);
            inline for (fields, 0..) |field, index| {
                paths[index] = try jsonPath(allocator, field.name);
                path_count += 1;
                entries[index] = .{
                    .column = field.name,
                    .Properties = .{ .Path = paths[index] },
                };
            }
            return serde.json.toSlice(allocator, entries);
        }

        fn jsonPath(allocator: std.mem.Allocator, field_name: []const u8) ![]u8 {
            var path = std.ArrayList(u8).empty;
            errdefer path.deinit(allocator);
            try path.appendSlice(allocator, "$['");
            for (field_name) |byte| {
                if (byte == '\\' or byte == '\'')
                    try path.append(allocator, '\\');
                try path.append(allocator, byte);
            }
            try path.appendSlice(allocator, "']");
            return path.toOwnedSlice(allocator);
        }
    };
}

test "direct bytes streaming uses gzip and a stable logical source ID" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );

    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        .{ .bytes = "hello streaming\n" },
        .{ .source_id = "source-1" },
    );
    defer result.deinit(allocator);
    try std.testing.expectEqualStrings("source-1", result.ok.ingestion_id.?);
    try std.testing.expectEqual(SourceKind.bytes, result.ok.source_kind.?);
    try std.testing.expectEqualStrings("gzip", transport.last_headers.get("Content-Encoding").?);
    try std.testing.expectEqualStrings("source-1", transport.last_headers.get("x-ms-client-request-id").?);
    try std.testing.expectEqual(false, transport.last_retryable.?);

    var compressed = std.Io.Reader.fixed(transport.last_body.?);
    var inflate_buffer: [std.compress.flate.max_window_len]u8 = undefined;
    var inflater = std.compress.flate.Decompress.init(&compressed, .gzip, &inflate_buffer);
    const body = try inflater.reader.allocRemaining(allocator, .unlimited);
    defer allocator.free(body);
    try std.testing.expectEqualStrings("hello streaming\n", body);
}

const StreamingToken = struct {
    credential: core.credentials.TokenCredential = .{ .getTokenFn = &getToken },

    fn getToken(
        _: *core.credentials.TokenCredential,
        _: core.credentials.TokenRequestContext,
        _: core.context.Context,
    ) anyerror!core.credentials.AccessToken {
        return .{
            .token = "streaming-token",
            .expires_on = std.math.maxInt(i64),
        };
    }
};

test "shared connections authenticate streamed reader uploads" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var token = StreamingToken{};
    const connection = try KustoConnection.init(
        allocator,
        .{
            .cluster_url = "https://cluster.kusto.windows.net",
            .credential = &token.credential,
        },
        transport.asTransport(),
        .{ .metadata_mode = .disabled },
    );
    defer connection.deinit();
    var reader = std.Io.Reader.fixed("authenticated reader");
    var client = StreamingIngestClient.initWithConnection(connection);
    var result = try client.ingestFromReaderResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        &reader,
        "authenticated reader".len,
        .{},
    );
    defer result.deinit(allocator);
    try std.testing.expectEqualStrings(
        "Bearer streaming-token",
        transport.last_headers.get("Authorization").?,
    );
    try std.testing.expectEqual(SourceKind.reader, result.ok.source_kind.?);
}

test "direct URI source uses typed JSON and sourceKind uri" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        .{ .blob_uri = .{
            .uri = "https://storage.example/container/a b.json?sig=a&b",
            .raw_size = 4,
        } },
        .{ .compression = .none },
    );
    defer result.deinit(allocator);
    try std.testing.expect(std.mem.indexOf(u8, transport.last_url.?, "sourceKind=uri") != null);
    try std.testing.expectEqualStrings(
        "{\"sourceUri\":\"https://storage.example/container/a b.json?sig=a&b\"}",
        transport.last_body.?,
    );
    try std.testing.expect(transport.last_headers.get("Content-Encoding") == null);
}

test "file sources are streamed through open without whole-file buffering" {
    const allocator = std.testing.allocator;
    const path = ".kusto-streaming-ingest-file-test";
    var threaded: std.Io.Threaded = .init_single_threaded;
    const io = threaded.io();
    const cwd = std.Io.Dir.cwd();
    var file = try cwd.createFile(io, path, .{});
    {
        var write_buffer: [64]u8 = undefined;
        var writer = file.writerStreaming(io, &write_buffer);
        try writer.interface.writeAll("file source\n");
        try writer.interface.flush();
    }
    file.close(io);
    defer cwd.deleteFile(io, path) catch {};

    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestFromFileResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        path,
        .{ .compression = .none },
    );
    defer result.deinit(allocator);
    try std.testing.expectEqualStrings("file source\n", transport.last_body.?);
    try std.testing.expectEqual(SourceKind.file, result.ok.source_kind.?);
}

const ChunkedReader = struct {
    interface: std.Io.Reader,
    bytes: []const u8,
    offset: usize = 0,
    max_request: usize = 0,

    fn init(bytes: []const u8) ChunkedReader {
        return .{
            .interface = .{
                .vtable = &.{ .stream = &stream },
                .buffer = &.{},
                .seek = 0,
                .end = 0,
            },
            .bytes = bytes,
        };
    }

    fn stream(
        interface: *std.Io.Reader,
        writer: *std.Io.Writer,
        limit: std.Io.Limit,
    ) std.Io.Reader.StreamError!usize {
        const self: *ChunkedReader = @alignCast(@fieldParentPtr("interface", interface));
        const requested = limit.minInt(std.math.maxInt(usize));
        self.max_request = @max(self.max_request, requested);
        if (self.offset == self.bytes.len) return error.EndOfStream;
        const count = @min(
            self.bytes.len - self.offset,
            @min(requested, 4 * 1024),
        );
        try writer.writeAll(self.bytes[self.offset .. self.offset + count]);
        self.offset += count;
        return count;
    }
};

test "large readers use bounded gzip working storage" {
    const allocator = std.testing.allocator;
    const bytes = try allocator.alloc(u8, 1024 * 1024);
    defer allocator.free(bytes);
    @memset(bytes, 'x');
    var source = ChunkedReader.init(bytes);
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestFromReaderResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        &source.interface,
        bytes.len,
        .{},
    );
    defer result.deinit(allocator);
    try std.testing.expect(source.max_request <= 16 * 1024);
    try std.testing.expect(source.offset == bytes.len);
}

test "direct URL components are independently encoded" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB /&?=+", .table = "Table /&?=+" },
        .{ .bytes = "x" },
        .{ .mapping_name = "Mapping /&?=+", .compression = .none },
    );
    defer result.deinit(allocator);
    try std.testing.expectEqualStrings(
        "https://cluster.kusto.windows.net/v1/rest/ingest/DB%20%2F%26%3F%3D%2B/Table%20%2F%26%3F%3D%2B?streamFormat=Csv&mappingName=Mapping%20%2F%26%3F%3D%2B",
        transport.last_url.?,
    );
}

test "unsupported direct options fail before transport" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    try std.testing.expectError(
        error.StreamingExtentTagsUnsupported,
        client.ingestResult(
            allocator,
            .{ .database = "DB", .table = "Table" },
            .{ .bytes = "x" },
            .{ .tags = &.{"ingest-by:x"} },
        ),
    );
    try std.testing.expect(transport.last_url == null);
}

test "unsupported direct formats and required mappings fail before transport" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    try std.testing.expectError(
        error.StreamingFormatUnsupported,
        client.ingestResult(
            allocator,
            .{ .database = "DB", .table = "Table" },
            .{ .bytes = "x" },
            .{ .format = .parquet },
        ),
    );
    try std.testing.expectError(
        error.StreamingMappingRequired,
        client.ingestResult(
            allocator,
            .{ .database = "DB", .table = "Table" },
            .{ .bytes = "{}\n" },
            .{ .format = .json },
        ),
    );
    try std.testing.expect(transport.last_url == null);
}

test "reader sources require known raw size and are never retried" {
    const allocator = std.testing.allocator;
    var reader = std.Io.Reader.fixed("reader bytes");
    var transport = core.http.MockTransport.init(
        allocator,
        503,
        "{\"error\":{\"message\":\"retry\"}}",
    );
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );

    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        .{ .reader = .{ .reader = &reader, .raw_size = "reader bytes".len } },
        .{ .compression = .none },
    );
    defer result.deinit(allocator);
    try std.testing.expectEqual(@as(usize, 1), transport.call_count);
    try std.testing.expectEqual(KustoOperationOutcome.known_not_accepted, result.err.outcome);

    var missing_size = std.Io.Reader.fixed("x");
    try std.testing.expectError(
        error.StreamingRawSizeRequired,
        client.ingestResult(
            allocator,
            .{ .database = "DB", .table = "Table" },
            .{ .reader = .{ .reader = &missing_size } },
            .{},
        ),
    );
}

const ReplayFixture = struct {
    bytes: []const u8,
    opens: usize = 0,
    closes: usize = 0,
    reader: std.Io.Reader = undefined,

    fn open(context: *anyopaque) anyerror!ReplayReader {
        const self: *ReplayFixture = @ptrCast(@alignCast(context));
        self.opens += 1;
        self.reader = std.Io.Reader.fixed(self.bytes);
        return .{
            .reader = &self.reader,
            .context = context,
            .deinitFn = &close,
        };
    }

    fn close(context: ?*anyopaque) void {
        const self: *ReplayFixture = @ptrCast(@alignCast(context.?));
        self.closes += 1;
    }
};

test "replay factories reopen only after known retryable responses" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(
        allocator,
        503,
        "{\"error\":{\"message\":\"retry\"}}",
    );
    defer transport.deinit();
    transport.response_headers_list = &.{
        .{ .name = "Retry-After", .value = "10" },
    };
    var fixture = ReplayFixture{ .bytes = "retry body" };
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        .{ .replay_reader = .{
            .context = &fixture,
            .openFn = &ReplayFixture.open,
            .raw_size = "retry body".len,
        } },
        .{
            .compression = .none,
            .source_id = "stable-source-id",
            .retry = .{ .initial_delay_ms = 0, .max_delay_ms = 0 },
        },
    );
    try std.testing.expectEqual(@as(usize, 2), transport.call_count);
    try std.testing.expectEqual(@as(usize, 2), fixture.opens);
    try std.testing.expectEqual(@as(usize, 2), fixture.closes);
    defer result.deinit(allocator);
    try std.testing.expectEqual(KustoOperationOutcome.known_not_accepted, result.err.outcome);
    try std.testing.expectEqualStrings("stable-source-id", result.err.client_request_id.?);
    try std.testing.expectEqual(@as(?u64, 10_000), result.err.retry_after_ms);
}

test "source-aware retry delay honors server guidance and remains bounded" {
    try std.testing.expectEqual(
        @as(u64, 2_000),
        retryDelayMs(.{ .initial_delay_ms = 200, .max_delay_ms = 5_000 }, 3, 2_000),
    );
    try std.testing.expectEqual(
        @as(u64, 5_000),
        retryDelayMs(.{ .initial_delay_ms = 200, .max_delay_ms = 5_000 }, 3, 20_000),
    );
    try std.testing.expectEqual(
        @as(u64, 1_600),
        retryDelayMs(.{ .initial_delay_ms = 200, .max_delay_ms = 5_000 }, 3, null),
    );
}

test "payload limits and raw sizes are validated before transport" {
    const allocator = std.testing.allocator;
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    const too_large = try allocator.alloc(u8, @as(usize, @intCast(max_streaming_payload_bytes + 1)));
    defer allocator.free(too_large);
    try std.testing.expectError(
        error.StreamingPayloadTooLarge,
        client.ingestResult(
            allocator,
            .{ .database = "DB", .table = "Table" },
            .{ .bytes = too_large },
            .{},
        ),
    );
    try std.testing.expect(transport.last_url == null);
}

fn ingestAllocationFixture(allocator: std.mem.Allocator) !void {
    var transport = core.http.MockTransport.init(allocator, 200, "{}");
    defer transport.deinit();
    var client = StreamingIngestClient.init(
        .{ .cluster_url = "https://cluster.kusto.windows.net" },
        transport.asTransport(),
    );
    var result = try client.ingestResult(
        allocator,
        .{ .database = "DB", .table = "Table" },
        .{ .bytes = "allocation fixture" },
        .{},
    );
    defer result.deinit(allocator);
}

test "streaming ingestion releases all allocation failure paths" {
    try std.testing.checkAllAllocationFailures(
        std.testing.allocator,
        ingestAllocationFixture,
        .{},
    );
}

test "typed JSON rows serialize and release allocations" {
    const Row = struct {
        name: []const u8,
        count: u32,
        @"Log Level": []const u8,
        @"a.b": bool,
    };
    const Rows = JsonRows(Row);
    var rows = try Rows.ndjson(std.testing.allocator, &.{
        .{ .name = "one", .count = 1, .@"Log Level" = "info", .@"a.b" = true },
        .{ .name = "two", .count = 2, .@"Log Level" = "warn", .@"a.b" = false },
    });
    defer rows.deinit(std.testing.allocator);
    try std.testing.expectEqualStrings(
        "{\"name\":\"one\",\"count\":1,\"Log Level\":\"info\",\"a.b\":true}\n{\"name\":\"two\",\"count\":2,\"Log Level\":\"warn\",\"a.b\":false}\n",
        rows.bytes,
    );
    const mapping = try Rows.mapping(std.testing.allocator);
    defer std.testing.allocator.free(mapping);
    try std.testing.expectEqualStrings(
        "[{\"column\":\"name\",\"Properties\":{\"Path\":\"$['name']\"}},{\"column\":\"count\",\"Properties\":{\"Path\":\"$['count']\"}},{\"column\":\"Log Level\",\"Properties\":{\"Path\":\"$['Log Level']\"}},{\"column\":\"a.b\",\"Properties\":{\"Path\":\"$['a.b']\"}}]",
        mapping,
    );
}
